### ISSUE TITLE
the latest version does not work

### ISSUE THREAD

**Issue by ghost** [greeves12/BugManager#1]
add the cooldown to report again

**Comment by ghost** [comment]
look this error: 
https://hastebin.com/woxewiquge.vbs

**Comment by greeves12** [comment]
I'm having issues viewing your hastbin, could you either paste the error here or upload it to a pastebin thanks! Also, I've already implemented the cooldown.

**Comment by ghost** [comment]
https://pastebin.com/dRDFWpEH

**Comment by ghost** [comment]
then?

**Comment by greeves12** [comment]
Do you have ProtocolLib installed? If you do, try deleting the plugin folder.

**Comment by ghost** [comment]
i have protocolib

**Comment by greeves12** [comment]
Ok I'll investigate it. I'll let you know when its resolved, you'll automatically get updated.

**Comment by greeves12** [comment]
Issue has been resolved, you either have a corrupted server jar file, which I recommend you redownload a new one or you aren't running 1.12 or higher. 

java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/Packet

That line of code means it can't find that specific class in your server jar file. I would recommend you seek assistance on spigot as this isn't caused by BugManager.

If you have any further questions please open another support ticket and assign myself to it, thank you and have a great day!
